import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
//whatevr we write on this page applies on all the pages
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Full Stack Nextjs Website",
  description: "Generated by Diksha Kumari Chhetri",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
